### ISSUE TITLE
Recording/binding events to <select/> elements

### ISSUE THREAD

**Issue by DennisLoska** [checkly/puppeteer-recorder#41] opened 2019-01-16 16:25 UTC
Hey,

so I was trying to record a dropdown menu selection. The dropdown menu consist of semantic HTML5 (<select> and <option> elements). The issue is, that the recorder does not recognize the element at all. I tried to change the code in the CodeGenerator.js to register the event on a 'click' and not on a 'change' event, as it currently is, but that also did not work.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

I get this error from the finder-module:

Can't generate CSS selector for non-element node type.

So it seems the recorder somehow does not pass the correct element to the finder in order for it to find a selector.

I am sorry for the formatting, but for some reason the Markdown is not working here and I don't know how to fix that.

**Comment by tnolet** [comment] 2019-01-16 16:34
That sucks and thanks for reporting. We actually have an automated test for this. There must be some iinteraction with the newish finder function. This will probably be fixed in the upcoming release (there were other bugs too).

**Comment by DennisLoska** [comment] 2019-01-16 16:47
Thank you for responding so quickly. Do you know, when the next release will be out? And yes it is the finder function, which is giving the error in line 62:

`    if (input.nodeType !== Node.ELEMENT_NODE) {
        throw new Error("Can't generate CSS selector for non-element node type.");
    }`

**Comment by tnolet** [comment] 2019-01-23 14:23
@DennisLoska can you try this again with version v0.5.1 that was just released?

**Comment by tnolet** [comment] 2019-02-15 18:16
@DennisLoska one more try. Can you give the last release a whirl?

**Comment by DennisLoska** [comment] 2019-02-18 10:45
@tnolet Hey sorry for the late response.

So I tried to get the new version running, but after I do npm i && npm run dev and try to start recording I get this error:

Error handling response: TypeError: Cannot read property 'length' of undefined

Context

index.html

Stack Trace
webpack-internal:///./src/code-generator/CodeGenerator.js:102 (CodeGenerator._parseEvents)
webpack-internal:///./src/code-generator/CodeGenerator.js:81 (CodeGenerator.generate)
webpack-internal:///./node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js?!./src/popup/components/App.vue?vue&type=script&lang=js&:107 (eval)

The only event, which gets recorded is the *navigation event, when I click on a link. I hope this helps. If I get it running I will test the >select/> element again.

**Comment by tnolet** [comment] 2019-06-12 17:36
Closing this. Cannot reproduce. Newer versions have been successfully built by me and contributors. Probably a local problem.

**Closed by tnolet** 2019-06-12 17:36 UTC
