### ISSUE TITLE
not read event when element is frameset

### ISSUE THREAD

**Issue by sintret** [checkly/puppeteer-recorder#27] opened 2018-09-26 09:22 UTC
my html code like this following :

``<html>
<head>
<title>TESTING - Welcome</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta http-equiv="EXPIRES" content="0">
<meta http-equiv="PRAGMA" content="no-cache">

<script language="javascript">

</script>
</head>
<frameset border="0" rows="80,*,0">
<frame scrolling="NO" marginwidth=0 marginheight=5 name="top" SRC="common/banner.jsp">
<frameset cols="200,*">
<frame scrolling="AUTO" marginwidth=0 marginheight=1 name="toc"  SRC="common/menu.jsp">
<frame noresize="noresize" marginwidth=5 marginheight=5 name=CONTENT src="/retail/Welcome.do?action=result">
</frameset>
<frame scrolling="AUTO" marginwidth=5 marginheight=5 name=bottom src="common/bottom.jsp">
</frameset>
<noframes>
<body bgcolor="#FFFFFF" text="#000000">
</body>
</noframes``

**Comment by tnolet** [comment] 2018-09-30 18:06
@sintret this is not even a valid html page. Can you maybe post a full, valid piece of html so I can run a test? tnx

**Comment by sintret** [comment] 2018-10-11 06:02
Ok Thanks, i miss tag html.

**Comment by tnolet** [comment] 2019-01-22 10:41
closing this due to not providing reproduceable example

**Closed by tnolet** 2019-01-22 10:41 UTC
